{
 "title": "Golden Signals ",
 "description": "Golden signals (error, throughput, latency)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count[5m]))",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests per Endpoint",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (RequestPath) (count_over_time({service_name=~\".+\"} | json | RequestPath != \"\" [1h]))"
    }
   ]
  },
  {
   "title": "All Endpoint Latencies (<10mins)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "sum by (url_path) (\r\n  rate(http_server_request_duration_seconds_sum[10m])\r\n) \r\n/ \r\nsum by (url_path) (\r\n  rate(http_server_request_duration_seconds_count[10m])\r\n) * 1000",
     "legendFormat": "{{http_target}} - {{http_method}}"
    }
   ]
  },
  {
   "title": "Error Percentage > 20%",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (service_name) (\r\n    rate(http_server_request_duration_seconds_count{service_name=~\"Lgtm.*\", http_response_status_code=~\"5..\"}[5m])\r\n  ) \r\n  / \r\n  sum by (service_name) (\r\n    rate(http_server_request_duration_seconds_count{service_name=~\"Lgtm.*\"}[5m])\r\n  )\r\n) * 100 or (count by (service_name) (http_server_request_duration_seconds_count{service_name=~\"Lgtm.*\"}) * 0)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Latencies",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 13 },
   "targets": [
    {
     "expr": "topk(10, \r\n  sum by (http_route, service_name) (\r\n    rate(http_server_request_duration_seconds_sum{service_name=~\".+\"}[5m])\r\n  ) \r\n  / \r\n  (sum by (http_route, service_name) (\r\n    rate(http_server_request_duration_seconds_count{service_name=~\".+\"}[5m])\r\n  ) > 0)\r\n) * 1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Autologged Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".+\"} | json | level = \"error\""
    }
   ]
  }
 ]
}