server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

metrics_generator:
  processor:
    service_graphs: {}
    span_metrics: {}
    local_blocks:
      flush_to_storage: true
  
  storage:
    path: ./data/tempo/generator
    remote_write:
      - url: "http://localhost:9090/api/v1/write"
        send_exemplars: true

  traces_storage:
    path: ./data/tempo/wal

overrides:
  metrics_generator_processors: [service-graphs, span-metrics, local-blocks]

storage:
  trace:
    backend: local
    local:
      path: ./data/tempo
    wal:
      path: ./data/tempo/wal